<?php
// src/OC/AppBundle/Repository/BilletRepository.php

namespace OC\AppBundle\Repository;

/**
 * BilletsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{
}
