<?php

namespace OC\AppBundle\Repository;

/**
 * VisiteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteursRepository extends \Doctrine\ORM\EntityRepository
{
}
