<?php
// src/OC/AppBundle/Repository/VisiteurRepository.php

namespace OC\AppBundle\Repository;

/**
 * VisiteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
{
}
